services:
  postgres:
    image: postgres:15
    container_name: postgres15
    environment:
      POSTGRES_DB: grafi_test_db
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: testing
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "listen_addresses=*"]
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pg_admin_email}
      PGADMIN_DEFAULT_PASSWORD: ${pg_admin_password}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    
  mcp_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: mcp_server
    ports:
      - "8081:8081"
    volumes:
      - ./contracts:/app/contracts
      - ./node_modules:/app/node_modules
    environment:
      - metamask_private_key=${metamask_private_key}
      - ethereum_sepolia_rpc=${ethereum_sepolia_rpc}
      - wallet_address=${wallet_address} 
  
  client:
    build: .
    container_name: grafi_client
    depends_on:
      postgres:
        condition: service_started
      mcp_server:
        condition: service_started
    volumes:
      - .:/app
      - /app/.venv
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - mcp_server_url=${mcp_server_url}
